---
dependencies: []

galaxy_info:
  role_name: apache2
  author: ubzyhd
  description: A ansible role to install Apache2 + apply basic security and hardening settings.
  company: Ubzy

  license: "license (BSD, MIT)"

  min_ansible_version: 2.8

  platforms:
    - name: Debian
      versions:
        - buster
        - stretch

  galaxy_tags:
    - server
    - system
    - common
    - debian
    - web
    - webserver
    - apache
    - apache2
    - httpd
